### ISSUE TITLE
Reader : improve hole management and clean the code

### ISSUE THREAD

**Issue by mfe** [tuttleofx/TuttleOFX#101]
Cf commits : 
8d364b069dacc96e8fa408b1c815071d8cebe9c8
530b3ab96a81bd3b46bb509cd8f0a22e6354f097
478d7c5bc04fc63dab8c88e31b46797038913fce
58329f9c612bbba974b2949d565d34d5a6d39d8b

**Comment by cchampet** [comment]
Outdated issue: too much changes since this issue.
