### ISSUE TITLE
Wrong error message when inputting an unsupported pixel depth 

### ISSUE THREAD

**Issue by mfe** [tuttleofx/TuttleOFX#170]
When using an unsupported pixel depth on a plugin, the resulting error message is "Segmentation Fault"

Ex : sam do constant explicitConversion=32 // swscale // viewer (swscale supports only 8 and 16 bits)

Message should be : "Unsupported input bitdepth".

**Comment by cchampet** [comment]
With last version of the host (0.11.0), the command line you given produce the correct error:
```
Error in graph bit depth propagation.
```
