### ISSUE TITLE
Param: add units support in setExpression

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#190]
Could be useful to set the bit rate with b=36M instead of b=36000000.
Need to define the list of useful units.

? T => 10e12
G => 10e9
M => 10e6
K => 10e3
? m => 10e-3
? u => 10e-6
? n => 10e-9

Go => 1024*1024*1024
Mo => 1024*1024
Ko => 1024

50% => 0.5

? 3h56m23s => seconds
...

**Comment by cchampet** [comment]
Still with the last version of AudioVideo plugin, we support expressions in presets given as input (like @MarcAntoine-Arnaud said).

And I don't think this is the role of the host to convert given expression and forward them to the plugins after conversion: each plugin (we are talking about io here) is based on a library with its own behavior and possibly conversion from a 'raw user input' to the interested information. Try to generalized this issue in the host is a very complicated feature I fear...
