### ISSUE TITLE
Log sam-do output to stderr instead of stdout

### ISSUE THREAD

**Issue by shahriman** [tuttleofx/TuttleOFX#195]
Right now, sam-do will print status messages to stdout which makes it impossible to pipe tuttle output with another program (say, ffmpeg) without using named pipes. To the best of my knowledge, the output that sam-do is printing to stdout ("process at time ..." and so on) are more suitable for stderr.

Of course changing sam-do is not enough. The whole codebase will have to be checked and  we will have to ensure that no plugins write status / error messages to stdout.

This will break binary compatibility of sam-do with previous release, but I think it's worth while in the long run. IMO, printing log output to stderr is the standard behavior.

**Comment by cchampet** [comment]
Done with the new sam in python:
* helps are displayed into stdcout
* debug info are displayed into stderr
