### ISSUE TITLE
sam-do: process simple sequence

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [tuttleofx/TuttleOFX#215]
sam do turbojpegr ####.jpg // w ####.png don't work
but this it's okay:
sam do turbojpegr ./####.jpg // w ./####.png

**Comment by cchampet** [comment]
I think it's because the shell has already processed the given input. There is no evident solution for this problem....
These command lines work for me:
```
sam do turbojpegr "####.jpg" // w "####.png"
sam do turbojpegr @@@@.jpg // w @@@@.png
```
