### ISSUE TITLE
sam do --file-formats

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#237]
Add an option to list all supported file formats R/W.

**Comment by cchampet** [comment]
No other than solutions than create a node for each available readers/writers, and get for each one its 'kTuttleOfxImageEffectPropSupportedExtensions' property?
@fabiencastan ?

**Comment by fabiencastan** [comment]
No the property is defined on the plugin descriptor, like here:
https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/io/OpenImageIO/src/reader/OpenImageIOReaderPluginFactory.cpp#L59
So you don't need to create an instance to read this property.
