### ISSUE TITLE
sam mv: can't move invalid symbolic link

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#259]
sam mv old.####.jpg new.####.jpg 

If "old.0001.jpg" is an invalid symbolic link, nothing is done and there is no erreur message.

**Comment by cchampet** [comment]
Since python version of sam -mv (403da8f8839f33bb647be9ed6a25747e5a3b4afb), invalid symbolic link are copied as same as valid symbolic link.
