### ISSUE TITLE
sam-do -h simplification

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#266]
Maybe we could remove from sam-do help, parameters declared with: kOfxParamPropEvaluateOnChange == false.

From the OFX documentation: kOfxParamPropEvaluateOnChange
"This is used to indicate if the value of a parameter has any affect on an effect's output, eg: the parameter may be purely for GUI purposes, and so changing its value should not trigger a re-render."
If it's purely GUI is has no sense in command line...

For example:
sam do crop -h
...
overlay                  : Boolean        0
          Display overlay rectangle
...

This option has no interest in command line.

**Comment by cchampet** [comment]
Why some parameters, like preset parameter of the Crop plugin, is declared with [kOfxParamPropEvaluateOnChange=false](https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/process/geometry/Crop/src/CropPluginFactory.cpp#L113)? Is it a mistake?

**Comment by fabiencastan** [comment]
No it's not a mistake.
The preset param in itself doesn't modify the output image. It's just a parameter that changes other params... and thoses params will modify the output.

**Comment by cchampet** [comment]
I got it. But hid 'preset' parameter from the node help is not a good idea I think...

**Comment by fabiencastan** [comment]
yes
