### ISSUE TITLE
sam-do generic readers/writers options are loosed

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#275]
sam do r data/seq.###.jpg // invert // w data2/b_###.png channel=gray plop=234

The writer revieve "channel=gray plop=234" arguments and return the error:
"Attribute name "plop" not found."

The same thing using a generic writer loose these options:
sam do r data/seq.###.jpg // invert // w data2/ ext=png channel=gray plop=234

"channel=gray plop=234" are ignored.

**Comment by cchampet** [comment]
Since sam-do is in python, we don't loose specific options with generic readers/writers.
