### ISSUE TITLE
Clean and migrate libav-presets repo in tuttleofx organisation

### ISSUE THREAD

**Issue by mfe** [tuttleofx/TuttleOFX#280]
Cf https://github.com/MarcAntoine-Arnaud/libav-presets

**Comment by cchampet** [comment]
libav preset are handle in the avtranscoder project (which is currently a submodule of Tuttle)
Cf https://github.com/mikrosimage/avTranscoder/tree/develop/ressource

**Comment by fabiencastan** [comment]
Is it correctly deployed with "make install"?
Is it directly used with relative paths?

**Comment by cchampet** [comment]
Yes the presets are deployed when "make install", in tuttle/share/ressource
But to use them, we need to set AVPROFILES environment variable.
I will create an issue in avtranscoder repository to set path by default.

**Comment by cchampet** [comment]
Done here: https://github.com/mikrosimage/avTranscoder/pull/91

**Comment by fabiencastan** [comment]
Maybe we could also add an ofx parameter in the plugin to see and modify the preset path.

**Comment by cchampet** [comment]
Will this work even if the preset path is an environment variable ?

**Comment by fabiencastan** [comment]
Retrieve the default value from avTranscoder to initialize the param and set the new value when the param is modified.

**Comment by MarcAntoine-Arnaud** [comment]
if it's FFmpeg/libav compliant preset, why create a new extension "prf" ?

**Comment by fabiencastan** [comment]
@MarcAntoine-Arnaud What is the ffmpeg/libav preset extension?

**Comment by MarcAntoine-Arnaud** [comment]
ffpreset
You can found some here:
https://github.com/joeyblake/FFmpeg-Presets
or also in the official reposirtory, deployed in shared resources:
https://github.com/FFmpeg/FFmpeg/tree/master/presets

**Comment by cchampet** [comment]
I didn't know about these ffmpeg presets... I could be great to be compliant with these FFmpeg/libav preset (we are close).

**Comment by MarcAntoine-Arnaud** [comment]
Yes, it as a little non-sense to have some presets in this library I think.
Or it can be fine to have presets in json ... But requires a dependency to parse it, and FFmpeg has no json parser.
And it's not present on the API to load presets file (Cf. https://github.com/FFmpeg/FFmpeg/blob/master/cmdutils.c#L1921), maybe we need to ask to expose that.

**Comment by cchampet** [comment]
Yes I will do that.
