### ISSUE TITLE
AVwriter default settings throw a fatal error

### ISSUE THREAD

**Issue by mfe** [tuttleofx/TuttleOFX#281]
`sam do r seq@.jpg // w movie.mov`
avwriter: unknown error : colorspace ( 0 )
unknown error
__________
Error: avWriter: unable to write header.
__________
[sam-do] Error

We should have a default behaviour or preset that enable anyone to export a generic movie easily.

Question : what should be this generic movie ? 
raw video ? dnxhd ?
mov ? mp4 ?
how about quality ?

Anyone, ideas ?
@MarcAntoine-Arnaud @reytrace

**Comment by cchampet** [comment]
Resolved with new version of AudioVideo plugin (4.0).
