### ISSUE TITLE
sam rm subrange

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#299]
We often need to remove a subrange of a sequence.
sam rm /datas/faca/data_seq/img_###.jpg --first-image 16 --last-image 28

Currently, you can't use first-image or last-image alone as expected...
sam rm /datas/faca/data_seq/img_###.jpg --first-image 16
The above command line should remove all frames after 16.

To remove a range, a dedicated option could be shorter:
sam rm /datas/faca/data_seq/img_###.jpg --range 16,28

**Comment by cchampet** [comment]
For the last two lines, see issue #155
