### ISSUE TITLE
Python binding need GLIBC_2.14

### ISSUE THREAD

**Issue by Narann** [tuttleofx/TuttleOFX#316]
Hi TuttleOFX team! :)

We need to use a kind of "python compositing" and TuttleOFX is certainly the current best choice (pay a Nuke licence to generate .mov is sad...).

We know TuttleOFX is very hard to compile (I never succeed actually, both at work and at home. I push for CMake here) so I've been surprised seeing a [builds](http://www.tuttleofx.org/download) page, thank you so much to provide auto builds! (But CMake could solve the problem and... Anyway).

So we tried. We are on the latest [CentOS](https://www.centos.org/) (version 6.5) and have troubles with python module _tuttle.so about library stuff:
~~~python
>>> import pyTuttle.tuttle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyTuttle/tuttle.py", line 30, in <module>
    _tuttle = swig_import_helper()
  File "pyTuttle/tuttle.py", line 26, in swig_import_helper
    _mod = imp.load_module('_tuttle', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by pyTuttle/_tuttle.so)
~~~
FYI: CentOS 6.5 libc version:
~~~bash
$ ll /lib64/libc.so.6
lrwxrwxrwx. 1 root root 12 Jan 30 12:44 /lib64/libc.so.6 -> libc-2.12.so
~~~
I know it's a little old [May 2010](https://en.wikipedia.org/wiki/GNU_C_Library#Version_history) but it's what latest CentOS use so...

See what is in _tuttle.so:
~~~bash
$ objdump -p _tuttle.so 

_tuttle.so:     file format elf64-x86-64

blahblah...

Version References:
  required from libgcc_s.so.1:
    0x0b792650 0x00 14 GCC_3.0
    0x0b792654 0x00 13 GCC_3.4
  required from libdl.so.2:
    0x09691a75 0x00 10 GLIBC_2.2.5
  required from libm.so.6:
    0x09691a75 0x00 08 GLIBC_2.2.5
  required from libc.so.6:
    0x06969194 0x00 11 GLIBC_2.14 << Problem is here
    0x09691a75 0x00 05 GLIBC_2.2.5
  required from libstdc++.so.6:
    0x0297f861 0x00 12 GLIBCXX_3.4.11
    0x02297f89 0x00 09 GLIBCXX_3.4.9
    0x0297f865 0x00 07 GLIBCXX_3.4.15
    0x056bafd3 0x00 04 CXXABI_1.3
    0x08922974 0x00 03 GLIBCXX_3.4
  required from libpthread.so.0:
    0x09691a75 0x00 06 GLIBC_2.2.5
    0x09691972 0x00 02 GLIBC_2.3.2
~~~
Let's see why this version is used:
~~~bash
$ objdump -T _tuttle.so | fgrep GLIBC_2.14
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.14  memcpy
~~~
So it seems _tuttle.so use GLIBC_2.14 version for memcpy function.

Let's see what memcpy version of GLIBC my OS can support:
~~~bash
$ readelf -s /lib/libc.so.6  | grep -w memcpy
  1176: 009e4440   104 IFUNC   GLOBAL DEFAULT   12 memcpy@@GLIBC_2.0
  6781: 009e4440   104 IFUNC   GLOBAL DEFAULT   12 memcpy
~~~

Could you try to place this in your main header to make TuttleOFX compatible with CentOS?
~~~c
__asm__(".symver memcpy,memcpy@GLIBC_2.0");
~~~

If it succed it shoud give something like:
~~~bash
$ objdump -p _tuttle.so
...
Version References:
  required from libc.so.6:
    0x09691a75 0x00 02 GLIBC_2.0
~~~
And:
~~~bash
$ objdump -T _tuttle.so | grep memcpy
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.0 memcpy
~~~

This URLs help me to understand how the problem could have been solved:
* https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version
* http://www.trevorpounds.com/blog/?p=103

Thanks in advance and keep the good work! :)

**Comment by cchampet** [comment]
Hello there,
Few months ago we have switched to CMake build system.
And you can find binaries [here](https://github.com/tuttleofx/TuttleOFX/releases/tag/v0.12.1), but they could no work with old CentOS (not tested).
If you are still interested in getting TuttleOFX on your platform, you can test to build the project with this new configuration.

**Comment by Narann** [comment]
I'm sorry, I will not been able to test anymore. :(

Feel free to close the ticket.

Keep the good job! :)
