### ISSUE TITLE
sam-do: param limits

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#337]
Don't print param range value if limits are [-inf:inf].

**Comment by cchampet** [comment]
In python, with default max value of a double parameter (x=1.7976900000000001e+308):
```
math.isinf(x) # print False
```
Other suggestions?

**Comment by fabiencastan** [comment]
Check using ofx value:

kOfxFlagInfiniteMin
kOfxFlagInfiniteMax
