### ISSUE TITLE
File Locking on Windows

### ISSUE THREAD

**Issue by teskenazi** [tuttleofx/TuttleOFX#365]
From Wikipedia :
"Microsoft Windows uses three distinct mechanisms to manage access to shared files:

* using share-access controls that allow applications to specify whole-file access-sharing for read, write, or delete
* using byte-range locks to arbitrate read and write access to regions within a single file
* by Windows file systems disallowing executing files from being opened for write or delete access"

Does TuttleOFX locks files in any of these ways on Windows?

**Comment by fabiencastan** [comment]
AFAIK, we don't lock anything currently.
