### ISSUE TITLE
AudioVideo: seek at time (second) instead of frame

### ISSUE THREAD

**Issue by cchampet** [tuttleofx/TuttleOFX#371]
Need to up avtranscoder to 0.5.2 and use InputFile::seekAtTime(time)

**Comment by fabiencastan** [comment]
What's the goal here?
OFX standard works in frames. So the plugin discuss with the host in frames.

On the other hand, it could be interesting to support time in second on tuttleHost API (just a conversion with the fps of the node).

Or maybe the goal here is to be able to set the time offset in seconds in the AVReader?

**Comment by cchampet** [comment]
Yes my mistake, I realized that openFX works in frames...
I created this issue because I have a problem when seek at frame 0 for an image with this kind of command:
```
sam do avreader image.jpg // viewer
```
I need to investigate why... Any ideas ?
