### ISSUE TITLE
Deploy getBestPlugin

### ISSUE THREAD

**Issue by cchampet** [tuttleofx/TuttleOFX#374]

**Comment by cchampet** [comment]
+ envTuttle.py ....

**Comment by fabiencastan** [comment]
Should remove envTuttle.py and support these default variables natively (LIBAV_DATADIR, OFX_PLUGIN_PATH, TUTTLE_HOME).

The "Load libraries" part is not needed anymore.

**Comment by cchampet** [comment]
Yep agreed.

**Comment by cchampet** [comment]
What do you mean by "support these variables natively"?

**Comment by fabiencastan** [comment]
Just to check if these 3 variables have a correct default value.

**Comment by cchampet** [comment]
https://github.com/tuttleofx/TuttleOFX/pull/390
