### ISSUE TITLE
Check log of OfxhImage Destructor

### ISSUE THREAD

**Issue by cchampet** [tuttleofx/TuttleOFX#384]
https://github.com/tuttleofx/TuttleOFX/blob/3a408bd1f5242ae8ac903fe4df5958c811124ef6/libraries/tuttle/src/tuttle/host/ofx/OfxhImage.cpp#L154

Why this is printed? Should be warning instead of info?

**Comment by fabiencastan** [comment]
INFO is lower than WARNING which is the default log level.
So it's not printed by default.

**Comment by cchampet** [comment]
LGTM
