### ISSUE TITLE
Problem with the plug-in TuttleColorTransfer.

### ISSUE THREAD

**Issue by rcspam** [tuttleofx/TuttleOFX#398]
Here is an explanation:
https://github.com/MrKepzie/Natron/issues/587
https://groups.google.com/d/msg/natron-vfx/oN_7CWqldLc/P-8vkjLnnU4J
Regards

**Comment by cchampet** [comment]
Hello,
It seems that the plugin tries to get an roi from ```srcRef``` clip, even if it is not connected.
And so the plugin throw an exception... But does not crash.
How do you connect the colorTransfer node in your graph?

**Comment by rcspam** [comment]
Hi,
It's an issue discover by manuels...@gmail.com here: https://groups.google.com/forum/#!msg/natron-vfx/oN_7CWqldLc/P-8vkjLnnU4J
Apparently, this plugin crash Natron when 'Src' and 'SrcRef'  are connect to the same node and if we 'slide' with some parameters....
Natron and video files are here:
https://groups.google.com/d/msg/natron-vfx/oN_7CWqldLc/bWsv-LMN_1QJ
I hope it will help...
Regards
rcspam

**Comment by cchampet** [comment]
Ok I did not get that you 'slide' with some parameters. I will test the plugin with Nuke.

**Comment by cchampet** [comment]
I tested the plugin with both Nuke and Natron, and I did not reproduce the error... 
I used the plugin colorTransfer v2.0 on Nuke, and the colorTransfer deployed with Natron.

@rcspam  Can you detail the parameters values of the plugin when it crashes (what transformation colorspace...)?
Nevertheless, I detect a problem when the plugin gets the rod. I fixed it, but I don't think this is your problem.

**Comment by rcspam** [comment]
Use natron snapshot
Src = image-4.jpeg
DstRef = Reference.tga
then output node to viewer
and crash

**Comment by rcspam** [comment]
i use the tuttle brundle that is installed with Natron snapshot here: http://sourceforge.net/projects/natron/files/snapshots/linux64/repo/Natron_Linux_bundle_snapshot_x86-64bit.tgz/download

**Comment by rcspam** [comment]
Is the different sizes is important ?

**Comment by cchampet** [comment]
The different sizes is not a problem.
So we try to get this graph:
![uploads/29572df2-fd65-4cd1-8809-ab4c33007541/natron_colorTransfer.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F29572df2-fd65-4cd1-8809-ab4c33007541%2Fnatron_colorTransfer.png)
I created it with the same Natron version. Here I just connect to the view.

**Comment by rcspam** [comment]
It was ok for me also: https://groups.google.com/d/msg/natron-vfx/oN_7CWqldLc/kPQqNeoXJyYJ

but now i have the same issue than manuels...@gmail.com in the topic
Here is a screenshot:
https://dl.dropboxusercontent.com/u/2677320/screencast-2015-04-27_14.56.49.mp4

**Comment by rcspam** [comment]
I have closed this issue by error
