### ISSUE TITLE
getStringValue on pointer param may crash

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#417]
Can't call lexical_cast on a pointer.

**Comment by cchampet** [comment]
Where in the code?

**Comment by fabiencastan** [comment]
https://github.com/tuttleofx/TuttleOFX/blob/develop/libraries/tuttle/src/tuttle/host/ofx/property/OfxhPropertyTemplate.hpp#L216

**Comment by fabiencastan** [comment]
It's a bug in boost 1.48 which is now fixed.
https://svn.boost.org/trac/boost/ticket/6132
