### ISSUE TITLE
Verbose level

### ISSUE THREAD

**Issue by julietteTaka** [tuttleofx/TuttleOFX#458]
ComputeOptions::init modify the global verbose level.
Need to keep only one enum for the verbose level:
https://github.com/tuttleofx/TuttleOFX/blob/develop/libraries/tuttle/src/tuttle/host/ComputeOptions.hpp#L56

**Comment by cchampet** [comment]
Need to keep only this enum as global verbose level:
https://github.com/tuttleofx/TuttleOFX/blob/develop/libraries/tuttle/src/tuttle/common/utils/Formatter.hpp#L38

**Comment by cchampet** [comment]
Better solution: remove verbose notion from ComputeOptions class (which call the verbose level of the Formatter singleton...).
