### ISSUE TITLE
sam ls --script

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#571]
```
> sam ls -R --script
./folder    
|__ ./file.####.exr     [1:596] 596 files
```

Instead of

```
> sam ls -R --script
./folder/file.####.exr  [1:596] 596 files
```

`--relative-path` has no impact.

```
> sam ls * --script
./file.####.exr     [1:596] 596 files
./file.####.exr     [1:596] 596 files
```

In that case the folder is not printed.

Tested with v0.13.0.

**Comment by cchampet** [comment]
After this PR:

```
sam ls dir -R --script
folder    
file.####.exr     [1:596] 596 files
```

```
sam ls dir -R --script --relative-path
folder    
folder/file.####.exr     [1:596] 596 files
```

Still a problem with the --relative-path option when there is no 'dir' indicated in the command line.

**Comment by fabiencastan** [comment]
great

**Comment by cchampet** [comment]
And the bug of the relative-path explained above is fixed with the following commit: e5b8a06

**Comment by fabiencastan** [comment]
Does it still work if the user provides "." in input?
Or maybe we need to apply os.path.abspath on the input?

**Comment by cchampet** [comment]
It still works if the user provides "." in input.
**os.path.abspath('.')** and **os.getcwd()** produce the same result so it does not change anything.

**Comment by fabiencastan** [comment]
No, I mean:

```
        # translate user inputs to a list of InputToBrowse
        inputsToBrowse = []
        for inputPath in args.inputs:
            # if the input is a directory, add it and continue
            if os.path.isdir(inputPath):
                inputsToBrowse.append(InputToBrowse(inputPath)) ///<< here the input from the user can be "."
                continue
            # else split the input to a path and a filename
            subPath = os.path.dirname(inputPath)
            if not subPath:
                subPath = '.'
            filename = os.path.basename(inputPath)
            # add the path and the filename as an expression
            inputToBrowse = InputToBrowse(subPath) ///<< here subPath can be "."
            inputToBrowse.addFilter(filename)
            inputsToBrowse.append(inputToBrowse)
        # if no user input, will browse in the current working directory
        if not inputsToBrowse:
            inputsToBrowse.append(InputToBrowse('.')) ///<< here you replaced "." by "os.getcwd()"
```

**Comment by cchampet** [comment]
I think we should keep the relative path given by the user, since [the way we implement the --relative-path](https://github.com/tuttleofx/TuttleOFX/blob/develop/applications/sam/sam_ls.py#L161) uses the Item.getFolder() method.

If the browse is done with an absolute path, the Item.getFolder() will return an absolute path. Else, it will return a relative path which can be  used to display the item.

**Comment by fabiencastan** [comment]
Ok, my point was just to ensure that these 2 command lines give the same results:
`sam ls -R --script --relative-path`
`sam ls . -R --script --relative-path`

**Comment by cchampet** [comment]
Ok I understand. It seems to be the case with my tests.
So if there is no input in the command line (**sam ls -R --script --relative-path**),  we browse the current folder with '.' as argument, and we have the same result as **sam ls . -R --script --relative-path**.
