### ISSUE TITLE
"VERSION_GREATER" "3"

### ISSUE THREAD

**Issue by HaroldGerenton** [tuttleofx/TuttleOFX#587]
Hi I'm a student in a cinema school, I'm making a memoire about FLOSS and i'm kind of a newbie with all of this (but i'm learning a lot lately!)

when i run the ./configure here's my output : 

-- SequenceParser version is 1.2.1
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   regex
--   system
--   filesystem
--   locale
-- tuttleHost version is 0.13.3 (retrieved from version.hpp)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   unit_test_framework
CMake Error at applications/CMakeLists.txt:8 (if):
  if given arguments:

    "VERSION_GREATER" "3"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!

I already solved the java environment variables, but the application/CMakeList.txt says 

# Edit python scripts if the host is built with python3
if(${TUTTLE_PYTHON_VERSION} VERSION_GREATER "3")

how do I do solve this? my system is currently using python 2.7.9 as default

I've been stuck with this issue for weeks.
I'm currently using debian jessie stable with cmake 3.0.2 and the following boost package libboost-all-dev 1.62.0.1

Many thanks in advance,
Hal

**Comment by cchampet** [comment]
Hi Harold,
If your goal is to get Tuttle on your platform, we already buit binaries for you! Get the last release [here](https://github.com/tuttleofx/TuttleOFX/releases/tag/v0.13.3).
But if your goal is to compile Tuttle, it seems you need to define the __TUTTLE_PYTHON_VERSION__ variable when configuring the project:
```bash
./configure -DTUTTLE_PYTHON_VERSION=2.7
```

**Comment by HaroldGerenton** [comment]
Hi,
Thanks a lot, it works like a charm!
