### ISSUE TITLE
v0.13.3- Make fails on building target tuttlehost on OSX 10.11.6

### ISSUE THREAD

**Issue by mikelafuente** [tuttleofx/TuttleOFX#588]
I tried several thing to build v0.13.3, but I get the same error on OSX 10.11.6:

_[ 46%] Building CXX object libraries/tuttle/CMakeFiles/tuttleHost.dir/src/tuttle/common/utils/backtrace.cpp.o
[ 46%] Building CXX object libraries/tuttle/CMakeFiles/tuttleHost.dir/src/tuttle/common/utils/color.cpp.o
2 warnings generated.
[ 46%] Linking CXX shared library libtuttleHost.dylib
[ 46%] Built target tuttleHost
make[1]: *** [all] Error _2_
make: *** [all] Error 2
bash-3.2$_ 

This is steps to reproduce:

git clone --recursive git://github.com/tuttleofx/TuttleOFX.git
cd TuttleOFX
./configure -DTUTTLE_PYTHON_VERSION=2.7
make

**Comment by cchampet** [comment]
Hello,
Can you get more logs? You can run __make__ with the additional argument "VERBOSE=1"
By the way, on OSX you can [use hombebrew to install tuttle](https://github.com/tuttleofx/TuttleOFX/blob/develop/INSTALL-ext-macos.md).

**Comment by mikelafuente** [comment]
Hello, 
Thanks for the quick response! Sorry, I forgot to attached the log yesterday. BTW, I originally tried homebrew, but the build dies at the same place. 
[CMakeOutput.log.zip](https://github.com/tuttleofx/TuttleOFX/files/784089/CMakeOutput.log.zip)

**Comment by cchampet** [comment]
Arg I don't understand what's wrong in this log... @fabiencastan do you have an idea?

**Comment by fabiencastan** [comment]
There is nothing wrong in the "CMakeOutput.log".
Can you provide the "CMakeError.log"?

**Comment by mikelafuente** [comment]
Unfortunately, I'm not finding  'CMakeError.log' anywhere on my machine. Regardless, I re-ran make with the VERBOSE=1 flag and piped it to the attached file. 
[Shell_log.txt](https://github.com/tuttleofx/TuttleOFX/files/822790/Shell_log.txt)

**Comment by cchampet** [comment]
This new log file gives us new info :) It seems that the avTranscoder dependency does not compile. I think CMake detected an ffmpeg version which is not supported. The easiest solution for now is to deactivate the AudioVideo plugin: please comment [this line](https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/CMakeLists.txt#L4) and recompile.

**Comment by mikelafuente** [comment]
Thanks for your help, that did the trick! Coincidently, I ran into another issue with jpg2K (see attached), so I also disabled it as well. Then I was able to finish compiling the code.

[j2kerror.txt](https://github.com/tuttleofx/TuttleOFX/files/826044/j2kerror.txt)
